//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDevamLinq
{
    using System;
    using System.Collections.Generic;
    
    public partial class OGRENCILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OGRENCILER()
        {
            this.NOTLAR = new HashSet<NOTLAR>();
        }
    
        public int OGRENCIID { get; set; }
        public string OGRENCIAD { get; set; }
        public string OGRENCISOYAD { get; set; }
        public string OGRENCIFOTO { get; set; }
        public Nullable<short> OGRKULUP { get; set; }
        public string SEHIR { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTLAR> NOTLAR { get; set; }
    }
}
